# Generated by Django 5.2.4 on 2025-07-15 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_post_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('vacancy', 'Vacancy'), ('result', 'Result'), ('exam', 'Exam Date'), ('admit_card', 'Admit Card'), ('answer_key', 'Answer Key')], max_length=20),
        ),
    ]
