# Generated by Django 5.2.4 on 2025-07-15 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_subscriber'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='description',
            field=models.TextField(blank=True, help_text='Detailed job information, eligibility, instructions, etc.'),
        ),
    ]
